### ISSUE TITLE
 No provider for ComponentLoaderFactory!

### ISSUE THREAD

**Issue by anchitjindal91** [tabler/tabler-angular#13]
Getting Below error.

header-notifications.component.ts.HeaderNotificationsComponent.html:2 ERROR Error: StaticInjectorError(AppModule)[BsDropdownDirective -> ComponentLoaderFactory]: 
  StaticInjectorError(Platform: core)[BsDropdownDirective -> ComponentLoaderFactory]: 
    NullInjectorError: No provider for ComponentLoaderFactory!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at NgModuleRef_.get (core.js:12087)
    at resolveDep (core.js:12577)

**Comment by gauravsaini03** [comment]
Can you please explain in detail, what you are trying to achieve and where you are getting error ? Also, share the node/npm versions you are using. If you share you issue in detail someone surely will able to help quickly.

**Comment by beeman** [comment]
I think you need to import `BsDropdownModule.forRoot()` to fix this. Will add it to the project today!

**Comment by anchitjindal91** [comment]
Hey! Thanks it works :) 
In header.module.ts I have changed 
import { BsDropdownModule } from 'ngx-bootstrap' to import { BsDropdownModule } from 'ngx-bootstrap/dropdown'; 
And in imports changes BsDropdownModule to BsDropdownModule.forRoot()

**Comment by anishbharatha** [comment]
The above solution starts displaying the profile menu but styles messed up. 
Adding `class="dropdown-item"` to the `<ui-link/>` tags in `header-profile.component.ts` is the next step to get styles.

**Comment by beeman** [comment]
Thanks @anchitjindal91 and @anishbharatha .

I've not found the time yet to add this fix, I would love to merge a PR if either one sends them in. Happy to share some info is that's a first time :)

**Comment by anishbharatha** [comment]
Thanks @anchitjindal91 @beeman . Made the changes and created a PR.

**Comment by beeman** [comment]
Fixed by #11
