### ISSUE TITLE
Merge dev branch into master & release

### ISSUE THREAD

**Issue by RemiSirdata** [tabler/tabler-angular#21]
Hi,

thank you for your project very useful.
I investigated on UI issues on profile link (missing "dropdown-item" class on ui-link) but I saw it's already fixed in developer branch.

Can you merge into master, tag a 0.7.4 and release it on NPM?
Components works fine with Angular 7 FYI.
Are you still active on the project? I'll use your components for a long term project, if I do pull requests can you handle them?

Regards,
Rémi

**Comment by arunabhdas** [comment]
Merged develop to master 

https://github.com/tabler/tabler-angular/pull/22

**Comment by RemiSirdata** [comment]
Thx @arunabhdas 
Would be great to release a version 0.7.4 et publish them to npm project :
* @tabler/angular-styles
* @tabler/angular-ui
* @tabler/angular-core
* @tabler/angular-forms

**Comment by arunabhdas** [comment]
Need @beeman to help with publish.

**Comment by evoxmusic** [comment]
Hi guys, Any update?

**Comment by beeman** [comment]
@arunabhdas if you get me your npm username I will add you to the org. Or if you want any other help we can jump on a short call, or shoot me an email 👍

**Comment by evoxmusic** [comment]
Thank you @beeman for your quick reply. Hope to get this update soon :)

**Comment by beeman** [comment]
Cool @evoxmusic! I'm super happy to see @arunabhdas picking up maintenance as I could not devote the time to it.

**Comment by evoxmusic** [comment]
Thanks @beeman and @arunabhdas . I will contribute the time I need this project. You did amazing work. @arunabhdas do not forget to update the modules version https://github.com/tabler/tabler-angular/blob/v0.7.5/libs/angular-core/package.json

**Comment by evoxmusic** [comment]
@arunabhdas do you have an ETA for this?

**Comment by arunabhdas** [comment]
Should be fine on master branch

https://github.com/tabler/tabler-angular/blob/master/libs/angular-core/package.json

**Comment by arunabhdas** [comment]
This should be fixed on 0.7.7 and higher.

**Comment by evoxmusic** [comment]
Thank you @arunabhdas 👍
