### ISSUE TITLE
make separate repositories

### ISSUE THREAD

**Issue by MetaiR** [tabler/tabler-angular#4]
Hello,
I think you have a modular structure here,
wouldn't it better for developing and using if they are in separated repositories?

I mean you could create 4 repos:
main project (tabler angular), its document, one module which you called it fire and one project for gathering them around by installing them with npm from github or npmjs repository itself. (for demo purposes or etc).

in current state when I want to use or contribute this project the least problem is I have to download other modules too and see their history and other stuff even if I don't want to change/use a single line of code on/from them.

**Comment by beeman** [comment]
Hey @MetaiR - thanks for your suggestion. 

Personally I think the structure is fine at this moment. Multiple repos make things generally more complex.

For me, this repo is where the 'reference implementation' of Tabler will be. Most of the things that will be built in this repo will be integrated in Tabler for Angular.

I see tabler-angular as a standalone project based on Tabler. It will have it's own documentation and demo projects, and will implement the Tabler UI in Angular, but will in the future use Tablers SCSS from NPM.

Soon I will create a `Tabler for Angular Start Kit` that people can use to quickly spin up a project with tabler-angular.

In line with this there could be a repos for `tabler-vue`, `tabler-react`, etc.

I hope this makes it clear. If not, please let me know.
